---
- name: Actualizar caché de los paquetes CentOS
  yum:
          name: '*'
          state: latest
          update_cache: true

#- name: Importar clave para repositorio remi-release
#  rpm_key:
#          key: https://rpms.remirepo.net/enterprise/9/RPM-GPG-KEY-remi
#          state: present

#- name: Habilitar repositorios
#  yum:
#          name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm, https://dl.fedoraproject.org/pub/epel/epel-next-release-latest-9.noarch.rpm
#          state: present

#- name: Habilitar módulo PHP 8.0 en Remi
#  command: dnf module enable php:remi-8.0 -y

- name: Instalar paquetes requeridos
  yum:
        name:
          - php
          - httpd
          - php-cli
          - php-fpm
          - php-mysqlnd
          - php-zip
          - php-devel
          - php-gd
          - php-mcrypt
          - php-mbstring
          - php-curl
          - php-xml
          - php-pear
          - php-bcmath
        state: latest

- name: Reiniciar modulo php-fpm si está instalado
  service:
          name: php-fpm
          state: restarted
  when: ansible_facts['services']['php-fpm'] is defined

- name: Abrir puerto para servicio http
  firewalld:
          service: http
          permanent: true
          state: enabled

- name: Reiniciar servicio firewalld y cargar los cambios del firewall
  service:
          name: firewalld
          state: reloaded

- name: Iniciar Apache web server
  service:
          name: httpd
          state: started
          enabled: true

- name: Copiar ficheros de WordPress
  unarchive:
          src: https://wordpress.org/latest.tar.gz
          dest: /var/www/html/
          remote_src: yes
          owner: apache
          group: apache
          mode: '0755'

- name: Establecer configuración de Wordpress
  template:
          src: /etc/ansible/recursos/wp-config.php
          dest: /var/www/html/wordpress/wp-config.php
          owner: apache
          group: apache
          mode: '0644'

- name: Reiniciar Apache web server
  service:
          name: httpd
          state: restarted

- name: Deshabilitar módulo SELinux
  template:
          src: /etc/ansible/recursos/config
          dest: /etc/selinux/config
          owner: root
          group: root
          mode: '0644'

- name: Reiniciar servidor
  reboot:
          reboot_timeout: 60
          post_reboot_delay: 30
